---
- name: Precaution clean up before setup
  include_tasks: cleanup.yml

- name: Include machines variables
  include_vars: machines.yml

- name: Install required plugins
  include_tasks: install_plugin.yml

- name: Create virtual machines
  include_tasks: create_vm.yml

- name: Run Cloyster setup
  include_tasks: run_cloyster.yml

- name: Clean up after setup
  include_tasks: cleanup.yml
  when: cleanup_needed