---
- name: Cloyster Vagrant Setup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Load configuration variables
      include_vars:
        file: "./config.yml"
        name: config_vars

  roles:
    - cloyster_setup